services:
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:4321:4321"
    command: sh -c "npm install && npm run dev -- --host"

  prod:
    build: .
    ports:
      - "0.0.0.0:4322:80"
    profiles:
      - prod
